# Nova CLI Configuration Example
# Copy this file to config.yaml and modify as needed

server:
  baseUrl: "http://localhost:4000"
  timeout: 30000

audio:
  sampleRate: 16000
  chunkDuration: 3.0
  silenceThreshold: -40
  silenceDuration: 2.0

wakeWord:
  confidenceThreshold: 0.2
  cooldownPeriod: 1.0